services:
  - type: web
    name: yazoni-plugin-downloader
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: ETERNALZERO_SFTP_HOST
        sync: false
      - key: ETERNALZERO_SFTP_PORT
        value: "2022"
      - key: ETERNALZERO_SFTP_USERNAME
        sync: false
      - key: ETERNALZERO_SFTP_PASSWORD
        sync: false
      - key: ETERNALZERO_SFTP_ROOT
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
