import type {ToolContext,ToolDefinition} from "@yazoni/core";
import {MinecraftRuntime} from "./server-runtime.js";

const approve=(c:ToolContext)=>{if(!c.dryRun&&!c.approved)throw new Error("Explicit approval is required.");};
const obj=(v:unknown)=>typeof v==="object"&&v!==null?v as Record<string,unknown>:{};
const str=(v:unknown)=>typeof v==="string"?v:"";

export function createConfigurationTools(runtime:MinecraftRuntime):ToolDefinition[]{
 return [
  {name:"config.server_properties.read",description:"Read server.properties as parsed key/value settings.",risk:"safe",input:{},execute:async()=>{const raw=await runtime.readFile("server.properties");const values:Record<string,string>={};for(const line of raw.split(/\r?\n/)){if(!line||line.startsWith("#"))continue;const i=line.indexOf("=");if(i>0)values[line.slice(0,i)]=line.slice(i+1);}return{values};}},
  {name:"config.server_properties.set",description:"Update one server.properties setting while preserving unrelated lines.",risk:"destructive",input:{key:"string",value:"string"},execute:async(input,c)=>{approve(c);const v=obj(input);const key=str(v.key).trim();const value=str(v.value);if(!/^[a-zA-Z0-9._-]{1,80}$/.test(key))throw new Error("Invalid property key.");if(/[\r\n]/.test(value))throw new Error("Property values must be a single line.");const raw=await runtime.readFile("server.properties");const lines=raw.split(/\r?\n/);let found=false;const next=lines.map(line=>{if(line.startsWith(key+"=")){found=true;return key+"="+value;}return line;});if(!found)next.push(key+"="+value);await runtime.writeFile("server.properties",next.join("\n"));return{updated:key,value,restartRecommended:true};}},
  {name:"config.server_properties.validate",description:"Check common server.properties values for obvious mistakes.",risk:"safe",input:{},execute:async()=>{const raw=await runtime.readFile("server.properties");const values:Record<string,string>={};for(const line of raw.split(/\r?\n/)){const i=line.indexOf("=");if(i>0&&!line.startsWith("#"))values[line.slice(0,i)]=line.slice(i+1);}const issues:string[]=[];if(values["server-port"]&&!/^\d+$/.test(values["server-port"]))issues.push("server-port must be numeric.");if(values["max-players"]&&(!/^\d+$/.test(values["max-players"])||Number(values["max-players"])<1))issues.push("max-players should be a positive integer.");if(values["online-mode"]!=="true"&&values["online-mode"]!=="false")issues.push("online-mode should be true or false.");if(values["view-distance"]&&(!/^\d+$/.test(values["view-distance"])||Number(values["view-distance"])<2||Number(values["view-distance"])>32))issues.push("view-distance is outside the commonly supported 2-32 range.");return{valid:issues.length===0,issues,checked:Object.keys(values).length};}},
  {name:"players.op",description:"Grant operator status to a Minecraft username.",risk:"destructive",input:{player:"string"},execute:async(input,c)=>{approve(c);const player=str(obj(input).player);if(!/^[a-zA-Z0-9_]{1,16}$/.test(player))throw new Error("Invalid Minecraft username.");return{output:await runtime.console("op "+player)};}},
  {name:"players.deop",description:"Remove operator status from a Minecraft username.",risk:"moderate",input:{player:"string"},execute:async(input,c)=>{approve(c);const player=str(obj(input).player);if(!/^[a-zA-Z0-9_]{1,16}$/.test(player))throw new Error("Invalid Minecraft username.");return{output:await runtime.console("deop "+player)};}},
  {name:"players.gamemode",description:"Change a player's game mode.",risk:"moderate",input:{player:"string",mode:"survival|creative|adventure|spectator"},execute:async(input,c)=>{approve(c);const v=obj(input);const player=str(v.player);const mode=str(v.mode);if(!/^[a-zA-Z0-9_]{1,16}$/.test(player)||!["survival","creative","adventure","spectator"].includes(mode))throw new Error("Invalid player or game mode.");return{output:await runtime.console("gamemode "+mode+" "+player)};}},
  {name:"players.give",description:"Give a player an item using a validated Minecraft item identifier and bounded quantity.",risk:"moderate",input:{player:"string",item:"string",amount:"number?"},execute:async(input,c)=>{approve(c);const v=obj(input);const player=str(v.player);const item=str(v.item);const amount=Math.floor(Number(v.amount??1));if(!/^[a-zA-Z0-9_]{1,16}$/.test(player)||! /^[a-z0-9_.-]+:[a-z0-9_./-]+$/.test(item)||!Number.isFinite(amount)||amount<1||amount>64)throw new Error("Invalid player, namespaced item ID, or amount (1-64).");return{output:await runtime.console("give "+player+" "+item+" "+amount)};}}
 ];
}
