import {promises as fs} from "node:fs";
import path from "node:path";
import {createHash} from "node:crypto";
import type {ToolContext,ToolDefinition,PluginCandidate} from "@yazoni/core";
import {ModrinthProvider,SpigotProvider} from "@yazoni/providers";
import {MinecraftRuntime} from "./server-runtime.js";

const approve=(c:ToolContext)=>{if(!c.dryRun&&!c.approved)throw new Error("This action requires explicit approval.");};
const object=(v:unknown)=>typeof v==="object"&&v!==null?v as Record<string,unknown>:{};
const text=(v:unknown)=>typeof v==="string"?v:"";

export function createManagementTools(runtime:MinecraftRuntime):ToolDefinition[]{
 const modrinth=new ModrinthProvider(); const spigot=new SpigotProvider();
 const backupsRoot=path.resolve(runtime.getServerRoot(),"..","."+path.basename(runtime.getServerRoot())+"-yazoni-backups");
 const tools:ToolDefinition[]=[
 {name:"plugins.search",description:"Search Modrinth for Minecraft plugins, optionally filtering by game version.",risk:"safe",input:{query:"string",minecraftVersion:"string?"},execute:async(input)=>{const v=object(input);const q=text(v.query).trim();if(!q)throw new Error("Search query required.");return{results:await modrinth.search(q,text(v.minecraftVersion)||undefined)};}},
 {name:"plugins.versions",description:"List published versions and dependency metadata for a Modrinth plugin.",risk:"safe",input:{projectId:"string"},execute:async(input)=>{const id=text(object(input).projectId).trim();if(!id)throw new Error("Project ID required.");return{versions:await modrinth.versions(id)};}},
 {name:"plugins.install",description:"Download and install a selected Modrinth plugin version into the server plugins directory.",risk:"destructive",input:{projectId:"string",version:"string?"},execute:async(input,c)=>{approve(c);const v=object(input);const id=text(v.projectId).trim();if(!id)throw new Error("Project ID required.");const versions=await modrinth.versions(id);const chosen=versions.find(x=>x.version===text(v.version))??versions[0];if(!chosen)throw new Error("No published versions found.");if(!chosen.downloadUrl)throw new Error("Selected version has no downloadable file.");const bytes=await modrinth.download(chosen);if(bytes.length<4||bytes[0]!==0x50||bytes[1]!==0x4b)throw new Error("Downloaded file does not appear to be a JAR/ZIP archive.");const safe=id.replace(/[^a-zA-Z0-9._-]/g,"-");const filename=safe+"-"+chosen.version.replace(/[^a-zA-Z0-9._-]/g,"-")+".jar";await runtime.writeBinary("plugins/"+filename,bytes);return{installed:true,filename,version:chosen.version,bytes:bytes.length,sha256:createHash("sha256").update(bytes).digest("hex"),restartRequired:true};}},
 {name:"plugins.list",description:"List files in the plugins directory.",risk:"safe",input:{},execute:async()=>({plugins:await runtime.listFiles("plugins").catch(()=>[])})},
 {name:"plugins.remove",description:"Remove a plugin jar from the plugins directory. Does not delete its configuration folder.",risk:"destructive",input:{filename:"string"},execute:async(input,c)=>{approve(c);const filename=path.basename(text(object(input).filename));if(!filename.endsWith(".jar")||filename!==text(object(input).filename))throw new Error("Provide a plugin jar filename, not a path.");await runtime.deleteFile("plugins/"+filename);return{removed:filename,restartRequired:true};}},
 {name:"worlds.list",description:"List directories under the Minecraft server worlds root.",risk:"safe",input:{},execute:async()=>({worlds:await fs.readdir(runtime.getServerRoot(),{withFileTypes:true}).then(es=>es.filter(e=>e.isDirectory()&&(/world/i.test(e.name)||e.name=== "world")).map(e=>e.name))})},
 {name:"worlds.create",description:"Create a new world by setting level-name and restarting the server. This does not merge worlds.",risk:"destructive",input:{name:"string"},execute:async(input,c)=>{approve(c);const name=text(object(input).name).trim();if(!/^[a-zA-Z0-9_-]{1,48}$/.test(name))throw new Error("World name must use 1-48 letters, numbers, underscores or hyphens.");const current=await runtime.readFile("server.properties").catch(()=> "");if(!current)throw new Error("server.properties is missing or unreadable.");const next=current.match(/^level-name=/m)?current.replace(/^level-name=.*$/m,"level-name="+name):current.trimEnd()+"\nlevel-name="+name+"\n";await runtime.writeFile("server.properties",next);return{configuredWorld:name,restartRequired:true,note:"Existing world folders are preserved. Restart to generate or load the selected world."};}},
 {name:"players.kick",description:"Kick a named player with an optional reason.",risk:"moderate",input:{player:"string",reason:"string?"},execute:async(input,c)=>{approve(c);const v=object(input);const player=text(v.player);if(!/^[a-zA-Z0-9_]{1,16}$/.test(player))throw new Error("Invalid Minecraft username.");const reason=text(v.reason).replace(/[\r\n]/g," ").slice(0,120);return{output:await runtime.console("kick "+player+(reason?" "+reason:""))};}},
 {name:"players.ban",description:"Ban a named player with an optional reason.",risk:"destructive",input:{player:"string",reason:"string?"},execute:async(input,c)=>{approve(c);const v=object(input);const player=text(v.player);if(!/^[a-zA-Z0-9_]{1,16}$/.test(player))throw new Error("Invalid Minecraft username.");const reason=text(v.reason).replace(/[\r\n]/g," ").slice(0,120);return{output:await runtime.console("ban "+player+(reason?" "+reason:""))};}},
 {name:"players.whitelist",description:"Add or remove a player from the vanilla whitelist.",risk:"moderate",input:{player:"string",enabled:"boolean"},execute:async(input,c)=>{approve(c);const v=object(input);const player=text(v.player);if(!/^[a-zA-Z0-9_]{1,16}$/.test(player))throw new Error("Invalid Minecraft username.");return{output:await runtime.console((v.enabled===false?"whitelist remove ":"whitelist add ")+player)};}},
 {name:"diagnostics.recent_console",description:"Read recent buffered console output for troubleshooting.",risk:"safe",input:{lines:"number?"},execute:async(input)=>{const n=Math.max(1,Math.min(500,Number(object(input).lines)||100));return{lines:runtime.getRecentConsole(n)};}},
 {name:"backups.create",description:"Create a point-in-time copy of server files outside the live server directory.",risk:"destructive",input:{label:"string?"},execute:async(input,c)=>{approve(c);await fs.mkdir(backupsRoot,{recursive:true});const stamp=new Date().toISOString().replace(/[:.]/g,"-");const label=text(object(input).label).replace(/[^a-zA-Z0-9_-]/g,"-").slice(0,32);const target=path.join(backupsRoot,stamp+(label?"-"+label:""));await fs.cp(runtime.getServerRoot(),target,{recursive:true,errorOnExist:true,filter:(src)=>!src.startsWith(backupsRoot)});return{created:true,path:target,note:"This is a file copy; for consistency, stop the server before backing up active world data."};}},
 {name:"backups.list",description:"List available local server snapshots.",risk:"safe",input:{},execute:async()=>({backups:await fs.readdir(backupsRoot,{withFileTypes:true}).then(es=>es.filter(e=>e.isDirectory()).map(e=>e.name)).catch(()=>[])})}
 ];
 return tools;
}
