"use client";
import {useEffect,useState} from "react";
type Version={id:string;name:string;gameVersions?:string[];loaders?:string[]};
type Result={id:string;name:string;description:string;icon?:string;downloads?:number;version?:string;source:"Modrinth"|"Spigot";versions?:Version[]};
export default function Home(){
 const[q,setQ]=useState("");const[source,setSource]=useState<"modrinth"|"spigot">("modrinth");const[results,setResults]=useState<Result[]>([]);const[popular,setPopular]=useState<Result[]>([]);const[loading,setLoading]=useState(false);const[message,setMessage]=useState("");const[password,setPassword]=useState("");const[searchOpen,setSearchOpen]=useState(false);const[version,setVersion]=useState<Record<string,string>>({});
 async function loadPopular(s=source){try{const r=await fetch("/api/search?source="+s+"&popular=1");const d=await r.json();setPopular(d.results??[])}catch{}}
 useEffect(()=>{loadPopular(source)},[source]);
 async function search(){if(q.trim().length<2)return;setLoading(true);setSearchOpen(true);setMessage("");try{const r=await fetch("/api/search?q="+encodeURIComponent(q)+"&source="+source);const d=await r.json();if(!r.ok)throw new Error(d.error);setResults(d.results??[])}catch(e){setMessage(e instanceof Error?e.message:"Search failed")}finally{setLoading(false)}}
 async function install(x:Result){const key=x.source+"-"+x.id;const versionId=version[key]||x.versions?.[0]?.id;setMessage("Installing "+x.name+" "+(x.versions?.find(v=>v.id===versionId)?.name||"")+" directly to the server…");try{const r=await fetch("/api/install",{method:"POST",headers:{"content-type":"application/json","x-admin-password":password},body:JSON.stringify({source:x.source,id:x.id,versionId})});const d=await r.json();if(!r.ok)throw new Error(d.error);setMessage("✓ Installed "+d.filename+" directly into /plugins.")}catch(e){setMessage(e instanceof Error?e.message:"Install failed")}}
 function card(x:Result){const key=x.source+"-"+x.id;return <article className="card" key={key}><div className="row">{x.icon&&<img className="icon" src={x.icon} alt=""/>}<div><div className="title">{x.name}</div><div className="muted">{x.source}{x.version?" · latest "+x.version:""}</div></div></div><p className="desc">{x.description||"No description available."}</p>{x.versions&&x.versions.length>0&&<select value={version[key]||x.versions[0].id} onChange={e=>setVersion(v=>({...v,[key]:e.target.value}))}>{x.versions.map(v=><option key={v.id} value={v.id}>{v.name}{v.gameVersions?.length?" · "+v.gameVersions.slice(0,3).join(", "):""}{v.loaders?.length?" · "+v.loaders.join(", "):""}</option>)}</select>}<div className="meta"><span className="muted">{x.downloads?.toLocaleString()??"—"} downloads</span><button className="install" onClick={()=>install(x)}>Install</button></div></article>}
 return <main className="wrap">
  <header className="top"><div><div className="brand">YAZONI PLUGIN DOWNLOADER</div><div className="sub">Find a plugin. Pick the version. Install it directly to your Minecraft server.</div></div></header>
  <div className="notice">Enter the admin password once, then every Install button sends the selected version straight to your EternalZero server.</div>
  <input value={password} onChange={e=>setPassword(e.target.value)} type="password" placeholder="Admin password" style={{width:"100%",background:"#111318",border:"1px solid #292d35",color:"white",borderRadius:10,padding:14,marginBottom:12}}/>
  <div className="search"><input value={q} onChange={e=>setQ(e.target.value)} onFocus={()=>setSearchOpen(true)} onKeyDown={e=>{if(e.key==="Enter")search()}} placeholder="Search for a plugin…"/><button onClick={search} disabled={loading}>{loading?"Searching…":"Search"}</button></div>
  <div className="tabs"><button className={"tab "+(source==="modrinth"?"active":"")} onClick={()=>{setSource("modrinth");setSearchOpen(false)}}>Modrinth</button><button className={"tab "+(source==="spigot"?"active":"")} onClick={()=>{setSource("spigot");setSearchOpen(false)}}>Spigot</button></div>
  {message&&<div className={"notice "+(message.startsWith("✓")?"success":"")}>{message}</div>}
  {!searchOpen&&<section className="popularPage"><div className="sectionHead"><h1>Popular plugins</h1><p>Most downloaded plugins on {source==="modrinth"?"Modrinth":"Spigot"} right now.</p></div><div className="grid">{popular.map(card)}</div></section>}
  {searchOpen&&<section className="searchPage"><div className="sectionHead"><h1>{loading?"Searching…":"Search results"}</h1><p>Choose the exact release you want before installing.</p></div><div className="grid">{results.map(card)}</div>{!loading&&!results.length&&<div className="empty">No plugins found.</div>}</section>}
 </main>
}