import type {PluginCandidate} from "@yazoni/core";
export interface PluginProvider{search(query:string,minecraftVersion?:string):Promise<PluginCandidate[]>;versions(id:string):Promise<PluginCandidate[]>;download(candidate:PluginCandidate):Promise<Uint8Array>}
export class ModrinthProvider implements PluginProvider{
 constructor(private readonly apiBase="https://api.modrinth.com/v2"){}
 async search(query:string,minecraftVersion?:string){const url=new URL(this.apiBase+"/search");url.searchParams.set("query",query);url.searchParams.set("facets",JSON.stringify(minecraftVersion?[["project_type:plugin"],["versions:"+minecraftVersion]]:[["project_type:plugin"]]));const r=await fetch(url);if(!r.ok)throw new Error("Modrinth search failed: "+r.status);const d=await r.json() as {hits?:Array<{project_id:string;title:string;latest_version?:string}>};return(d.hits??[]).map(h=>({id:h.project_id,name:h.title,source:"modrinth" as const,version:h.latest_version??"latest",minecraftVersions:minecraftVersion?[minecraftVersion]:[],dependencies:[]}))}
 async versions(id:string){const r=await fetch(this.apiBase+"/project/"+encodeURIComponent(id)+"/version");if(!r.ok)throw new Error("Modrinth versions failed: "+r.status);const d=await r.json() as Array<{version_number:string;game_versions:string[];dependencies:Array<{project_id?:string;version_id?:string;dependency_type?:string}>;files:Array<{url:string}>}>;return d.map(v=>({id,name:id,source:"modrinth" as const,version:v.version_number,minecraftVersions:v.game_versions,dependencies:v.dependencies.filter(x=>x.dependency_type!=="optional").map(x=>x.project_id??x.version_id??"").filter(Boolean),...(v.files[0]?.url?{downloadUrl:v.files[0].url}:{})}))}
 async download(candidate:PluginCandidate){if(!candidate.downloadUrl)throw new Error("No download URL is available.");const r=await fetch(candidate.downloadUrl);if(!r.ok)throw new Error("Plugin download failed: "+r.status);return new Uint8Array(await r.arrayBuffer())}
}
type SpigetResource={id:number;name:string;version?:string;testedVersions?:string[]};
type SpigetVersion={name?:string;version?:string};
export class SpigotProvider implements PluginProvider{
 private readonly api="https://api.spiget.org/v2";
 async search(query:string,minecraftVersion?:string){const u=new URL(this.api+"/search/resources/"+encodeURIComponent(query));u.searchParams.set("size","20");u.searchParams.set("sort","-downloads");const r=await fetch(u);if(!r.ok)throw new Error("Spigot resource search failed: "+r.status);const d=await r.json() as SpigetResource[];return d.filter(x=>!minecraftVersion||!x.testedVersions?.length||x.testedVersions.includes(minecraftVersion)).map(x=>({id:String(x.id),name:x.name,source:"spigot" as const,version:x.version??"latest",minecraftVersions:x.testedVersions??[],dependencies:[],downloadUrl:this.api+"/resources/"+x.id+"/download"}))}
 async versions(id:string){if(!/^\d+$/.test(id))throw new Error("Spigot resource ID must be numeric.");const [a,b]=await Promise.all([fetch(this.api+"/resources/"+id),fetch(this.api+"/resources/"+id+"/versions?size=20&sort=-releaseDate")]);if(!a.ok)throw new Error("Spigot resource lookup failed: "+a.status);const resource=await a.json() as SpigetResource;const versions=b.ok?await b.json() as SpigetVersion[]:[];const rows=versions.length?versions:[{version:resource.version??"latest"}];return rows.map(v=>({id,name:resource.name,source:"spigot" as const,version:v.version??v.name??"latest",minecraftVersions:resource.testedVersions??[],dependencies:[],downloadUrl:this.api+"/resources/"+id+"/download"}))}
 async download(candidate:PluginCandidate){if(candidate.source!=="spigot"||!/^\d+$/.test(candidate.id))throw new Error("Invalid Spigot resource.");const r=await fetch(this.api+"/resources/"+candidate.id+"/download",{redirect:"follow"});if(!r.ok)throw new Error("Spigot download failed: "+r.status);const bytes=new Uint8Array(await r.arrayBuffer());if(bytes.length<4||bytes[0]!==0x50||bytes[1]!==0x4b)throw new Error("Spigot response was not a JAR/ZIP archive.");return bytes}
}