import type{PluginCandidate}from"@yazoni/core";
export interface PluginProvider{search(query:string,minecraftVersion?:string):Promise<PluginCandidate[]>;versions(id:string):Promise<PluginCandidate[]>;download(candidate:PluginCandidate):Promise<Uint8Array>}
export class ModrinthProvider implements PluginProvider{
constructor(private readonly apiBase="https://api.modrinth.com/v2"){}
async search(query:string,minecraftVersion?:string){const u=new URL(this.apiBase+"/search");u.searchParams.set("query",query);u.searchParams.set("facets",JSON.stringify(minecraftVersion?[["project_type:plugin"],["versions:"+minecraftVersion]]:[["project_type:plugin"]]));const r=await fetch(u);if(!r.ok)throw new Error("Modrinth search failed: "+r.status);const d=await r.json() as{hits?:Array<{project_id:string;title:string}>};return(d.hits??[]).map(x=>({id:x.project_id,name:x.title,source:"modrinth" as const,version:"latest",minecraftVersions:minecraftVersion?[minecraftVersion]:[],dependencies:[]}))}
async versions(id:string){const r=await fetch(this.apiBase+"/project/"+encodeURIComponent(id)+"/version");if(!r.ok)throw new Error("Modrinth versions failed: "+r.status);const d=await r.json() as Array<{version_number:string;game_versions:string[];dependencies:Array<{project_id?:string;version_id?:string}>;files:Array<{url:string}>}>;return d.map(v=>({id,name:id,source:"modrinth" as const,version:v.version_number,minecraftVersions:v.game_versions,dependencies:v.dependencies.map(x=>x.project_id??x.version_id??"").filter(Boolean),downloadUrl:v.files[0]?.url}))}
async download(c:PluginCandidate){if(!c.downloadUrl)throw new Error("No verified download URL.");const r=await fetch(c.downloadUrl);if(!r.ok)throw new Error("Plugin download failed: "+r.status);return new Uint8Array(await r.arrayBuffer())}
}
export class SpigotProvider implements PluginProvider{async search(){return[]}async versions(){return[]}async download(){throw new Error("Spigot requires a verified resource adapter.")}}
